numberOfDataSources:
  type: static
  count: 7
caseId: increasing
type: debug
loadType: gradual
tickCount: 100
load: 10
minimalLoad: 5
dataSourceTopology:
  defaultSink:
    type: console
  dataSources:
  - name: "GoodsDelivery"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [0.1, 0.7, 0.2]
      from:
        events:
          - activity: "Reject"
            transition: 7
            duration: 1
          - activity: "Store"
            transition: 0
            duration:
              type: gaussian
              mu: 720
              sigma: 120
          - activity: "Pass To Production"
            transition: 1
            duration:
              type: uniform
              lowerBound: 3
              upperBound: 7
  - name: "MaterialPreparation"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.25, 0.7, 0.05 ]
      from:
        events:
          - activity: "MaterialPreparation - Finished"
            duration:
              type: uniform
              lowerBound: 1
              upperBound: 2
            transition: 2
          - activity: "Waiting for Material"
            transition: 1
            duration: 1
          - activity: "Internal Error"
            transition: 1
            duration:
              type: gaussian
              mu: 500
              sigma: 100
  - name: "AssemblyLineSetup"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.3, 0.4, 0.15, 0.05, 0.1 ]
      from:
        events:
          - activity: "Material Not Set Up as expected"
            transition: 1
            duration:
              type: uniform
              lowerBound: 2
              upperBound: 5
          - activity: "Assembly Line Setup successfully"
            transition: 3
            duration: 3
          - activity: "Material in wrong order. Reordering.."
            transition: 2
            duration: 1
          - activity: "Maximum Material count exceeded. Remove item"
            transition: 2
            duration: 1
          - activity: "Internal Error"
            transition: 3
            duration:
              type: gaussian
              mu: 500
              sigma: 100
  - name: "AssemblyProcess"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.8, 0.1, 0.08, 0.02 ]
      from:
        events:
          - activity: "Assembling completed"
            duration: 10
            transition: 4
          - activity: "Overheating"
            transition: 7
            duration: 2
          - activity: "Item broke"
            transition: 7
            duration: 1
          - activity: "Internal Error"
            transition: 3
            duration:
              type: gaussian
              mu: 500
              sigma: 100
  - name: "QualityControl"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [ 0.3, 0.1, 0.6 ]
      from:
        events:
          - activity: "Item Needs Corrections"
            transition: 3
            duration: 2
          - activity: "Quality Insufficient"
            transition: 7
            duration: 2
          - activity: "Quality check passed"
            transition: 5
            duration:
              type: uniform
              lowerBound: 5
              upperBound: 10
  - name: "Packaging"
    groupId: "factory"
    eventGeneration:
      selection: genericProbability
      distribution: [ 1.0 ]
      from:
        events:
          - activity: "Packaging completed"
            transition: 6
            duration: 3
  - name: "Shipping"
    groupId: "factory"
    eventGeneration:
      selection: uniform
      distribution: [ 0.8, 0.2 ]
      from:
        events:
          - activity: "Package waits for sending"
            transition: 6
            duration: 180
          - activity: "Package sent"
            transition: 7
            duration: 1